
import { createContext, useContext } from 'react';
import { useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'en' | 'ar';
  setLanguage: (lang: 'en' | 'ar') => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<'en' | 'ar'>((typeof window !== 'undefined' && localStorage.getItem('language')) === 'ar' ? 'ar' : 'en');

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', language);
      document.documentElement.setAttribute('lang', language);
      document.documentElement.setAttribute('dir', language === 'ar' ? 'rtl' : 'ltr');
    }
  }, [language]);

const translations = {
  en: {
    "Home": "Home",
    "Blog": "Blog",
    "Login": "Login",
    "Register": "Register",
    "Patient Dashboard": "Patient Dashboard",
    "Admin Dashboard": "Admin Dashboard",
    "Settings": "Settings",
    "Language": "Language",
    "Theme": "Theme",
    "Enable Registration": "Enable Registration",
    "Maintenance Mode": "Maintenance Mode",
    "Save": "Save",
    "Logout": "Logout",
    "Welcome": "Welcome",
    "Edit Profile": "Edit Profile",
    "View Blog": "View Blog",
    "Create Post": "Create Post",
    "Manage Users": "Manage Users",
    "Manage Content": "Manage Content",
    "System Settings": "System Settings",
    "Not Found": "Not Found",
    "Go Home": "Go Home",
    "All rights reserved": "All rights reserved",
    "Contact Us": "Contact Us",
    "About Us": "About Us",
    "Terms of Service": "Terms of Service",
    "Privacy Policy": "Privacy Policy",
    "Search": "Search",
    "Search...": "Search...",
    "No results found": "No results found",
    "Read more": "Read more",
    "Share": "Share",
    "Tags": "Tags",
    "Recent Posts": "Recent Posts",
    "Popular Posts": "Popular Posts",
    "Categories": "Categories",
    "Latest News": "Latest News",
    "Our Services": "Our Services",
    "Make Appointment": "Make Appointment",
    "Find a Doctor": "Find a Doctor",
    "Book Online": "Book Online",
    "View All": "View All",
    "Submit": "Submit",
    "Name": "Name",
    "Email": "Email",
    "Password": "Password",
    "Role": "Role",
    "Patient": "Patient",
    "Doctor": "Doctor",
    "Admin": "Admin",
    "Confirm Password": "Confirm Password",
    "Please enter your name": "Please enter your name",
    "Please enter your email": "Please enter your email",
    "Please enter your password": "Please enter your password",
    "Please select a role": "Please select a role",
    "Please confirm your password": "Please confirm your password",
    "Passwords must match": "Passwords must match",
    "Register as a new user": "Register as a new user",
    "Already have an account?": "Already have an account?",
    "Login here": "Login here",
    "Remember me": "Remember me",
    "Forgot password?": "Forgot password?",
    "Login to your account": "Login to your account",
    "Do not have an account?": "Do not have an account?",
    "Register here": "Register here",
    "Dashboard": "Dashboard",
    "Profile": "Profile",
    "Appointments": "Appointments",
    "Medical Records": "Medical Records",
    "Billing": "Billing",
    "Notifications": "Notifications",
    "Welcome back": "Welcome back",
    "Total Patients": "Total Patients",
    "New Appointments": "New Appointments",
    "Unread Messages": "Unread Messages",
    "View Details": "View Details",
    "Next Appointment": "Next Appointment",
    "No upcoming appointments": "No upcoming appointments",
    "Last Appointment": "Last Appointment",
    "No past appointments": "No past appointments",
    "Edit": "Edit",
    "Update Profile": "Update Profile",
    "Cancel": "Cancel",
    "Specialization": "Specialization",
    "Bio": "Bio",
    "Patients": "Patients",
    "Years of Experience": "Years of Experience",
    "Assigned Doctor": "Assigned Doctor",
    "Upcoming Appointment": "Upcoming Appointment",
    "Last Login": "Last Login",
    "Manage Settings": "Manage Settings",
    "Permissions": "Permissions",
    "Enable": "Enable",
    "Disable": "Disable",
    "Create New Post": "Create New Post",
    "Title": "Title",
    "Content": "Content",
    "Excerpt": "Excerpt",
    "Author": "Author",
    "Published Date": "Published Date",
    "Image URL": "Image URL",
    "Enter tags separated by commas": "Enter tags separated by commas",
    "Publish": "Publish",
    "Update Post": "Update Post",
    "Delete Post": "Delete Post",
    "Are you sure you want to delete this post?": "Are you sure you want to delete this post?",
    "Yes, Delete": "Yes, Delete",
    "No, Cancel": "No, Cancel",
    "Search Users": "Search Users",
    "Search by name or email": "Search by name or email",
    "Search Posts": "Search Posts",
    "Search by title or content": "Search by title or content",
    "Create User": "Create User",
    "Update User": "Update User",
    "Delete User": "Delete User",
    "Are you sure you want to delete this user?": "Are you sure you want to delete this user?",
    "Psychological Tests": "Psychological Tests",
    "Take one of our psychological tests to learn more about yourself.": "Take one of our psychological tests to learn more about yourself.",
    "Depression Test": "Depression Test",
    "Anxiety Test": "Anxiety Test",
    "Personality Test": "Personality Test",
    "ADHD Test": "ADHD Test",
    "Psychological State Test for Children": "Psychological State Test for Children",
    "Jealousy Test": "Jealousy Test",
    "Love Test": "Love Test",
    "Passion Test": "Passion Test",
    "This test will help assess potential symptoms. Results are not a diagnosis.": "This test will help assess potential symptoms. Results are not a diagnosis.",
    "Take this test to assess your": "Take this test to assess your",
    "The test consists of": "The test consists of",
    "questions and will take approximately": "questions and will take approximately",
    "minutes to complete.": "minutes to complete.",
    "Please answer each question honestly for the most accurate results.": "Please answer each question honestly for the most accurate results.",
    "Start Test": "Start Test",
    "Back": "Back",
    "Select": "Select",
    "Question": "Question",
    "of": "of",
    "Not at all": "Not at all",
    "Several days": "Several days",
    "More than half the days": "More than half the days",
    "Nearly every day": "Nearly every day",
    "Test Results": "Test Results",
    "This test is for educational purposes only and should not be used for self-diagnosis. Please consult with a mental health professional for proper diagnosis and treatment.": "This test is for educational purposes only and should not be used for self-diagnosis. Please consult with a mental health professional for proper diagnosis and treatment.",
    "Restart Test": "Restart Test",
    "Choose Another Test": "Choose Another Test",
    "Your score is": "Your score is",
    "Please consult with a professional for interpretation.": "Please consult with a professional for interpretation.",
    "Test completed!": "Test completed!",
    "Minimal or no depression": "Minimal or no depression",
    "Mild depression": "Mild depression",
    "Moderate depression": "Moderate depression",
    "Severe depression": "Severe depression",
    "Minimal or no anxiety": "Minimal or no anxiety",
    "Mild anxiety": "Mild anxiety",
    "Moderate anxiety": "Moderate anxiety",
    "Severe anxiety": "Severe anxiety",
    "I feel sad or down most of the day": "I feel sad or down most of the day",
    "I have lost interest in activities I used to enjoy": "I have lost interest in activities I used to enjoy",
    "I have trouble sleeping or sleep too much": "I have trouble sleeping or sleep too much",
    "I feel tired or have little energy": "I feel tired or have little energy",
    "I have poor appetite or am overeating": "I have poor appetite or am overeating",
    "I feel nervous or anxious": "I feel nervous or anxious",
    "I worry too much about different things": "I worry too much about different things",
    "I have trouble relaxing": "I have trouble relaxing",
    "I feel restless and have trouble sitting still": "I feel restless and have trouble sitting still",
    "I am easily annoyed or irritable": "I am easily annoyed or irritable",
    "I enjoy being the center of attention": "I enjoy being the center of attention",
    "I prefer quiet, solitary activities": "I prefer quiet, solitary activities",
    "I consider myself organized and detail-oriented": "I consider myself organized and detail-oriented",
    "I am comfortable in new social situations": "I am comfortable in new social situations",
    "I am more practical than creative": "I am more practical than creative",
    "I have difficulty maintaining attention": "I have difficulty maintaining attention",
    "I am easily distracted": "I am easily distracted",
    "I struggle to follow through on tasks": "I struggle to follow through on tasks",
    "I frequently lose things necessary for tasks": "I frequently lose things necessary for tasks",
    "I often fidget or feel restless": "I often fidget or feel restless",
    "The child has difficulty concentrating": "The child has difficulty concentrating",
    "The child seems worried or anxious": "The child seems worried or anxious",
    "The child has frequent mood swings": "The child has frequent mood swings",
    "The child has trouble making friends": "The child has trouble making friends",
    "The child has lost interest in activities they used to enjoy": "The child has lost interest in activities they used to enjoy",
    "I often worry about my partner being unfaithful": "I often worry about my partner being unfaithful",
    "I check my partner's phone or social media": "I check my partner's phone or social media",
    "I feel uncomfortable when my partner talks to others": "I feel uncomfortable when my partner talks to others",
    "I get upset when my partner gives attention to others": "I get upset when my partner gives attention to others",
    "I often need reassurance from my partner": "I often need reassurance from my partner",
    "I think about this person constantly": "I think about this person constantly",
    "I feel happy when I'm with this person": "I feel happy when I'm with this person",
    "I prioritize this person's needs over my own": "I prioritize this person's needs over my own",
    "I can see a future with this person": "I can see a future with this person", 
    "I accept this person's flaws": "I accept this person's flaws",
    "I lose track of time when engaged in this activity": "I lose track of time when engaged in this activity",
    "I feel energized when doing this activity": "I feel energized when doing this activity",
    "I constantly want to improve in this area": "I constantly want to improve in this area",
    "I think about this activity even when not doing it": "I think about this activity even when not doing it",
    "I would do this activity even if I wasn't paid or recognized for it": "I would do this activity even if I wasn't paid or recognized for it",
    "english": "English",
    "arabic": "Arabic",
    "login": "Log in",
    "signup": "Sign up",
    "my_account": "My Account",
    "admin_panel": "Admin Panel",
    "profile": "Profile",
    "logout": "Log out",
    "mental_health_resources": "Mental Health Resources",
    "explore_mental_health_blog": "Explore Our Mental Health Blog",
    "discover_insights": "Discover insights, tips, and information to support your mental wellbeing journey",
    "search_articles": "Search articles...",
    "no_articles_found": "No articles found",
    "try_adjusting_search": "Try adjusting your search or removing filters"
  },
  ar: {
    "Home": "الرئيسية",
    "Blog": "مدونة",
    "Login": "تسجيل الدخول",
    "Register": "تسجيل",
    "Patient Dashboard": "لوحة معلومات المريض",
    "Admin Dashboard": "لوحة تحكم المسؤول",
    "Settings": "إعدادات",
    "Language": "لغة",
    "Theme": "مظهر",
    "Enable Registration": "تمكين التسجيل",
    "Maintenance Mode": "وضع الصيانة",
    "Save": "حفظ",
    "Logout": "تسجيل الخروج",
    "Welcome": "مرحبا",
    "Edit Profile": "تعديل الملف الشخصي",
    "View Blog": "عرض المدونة",
    "Create Post": "إنشاء منشور",
    "Manage Users": "إدارة المستخدمين",
    "Manage Content": "إدارة المحتوى",
    "System Settings": "إعدادات النظام",
    "Not Found": "غير موجود",
    "Go Home": "العودة إلى الرئيسية",
    "All rights reserved": "جميع الحقوق محفوظة",
    "Contact Us": "اتصل بنا",
    "About Us": "معلومات عنا",
    "Terms of Service": "شروط الخدمة",
    "Privacy Policy": "سياسة الخصوصية",
    "Search": "بحث",
    "Search...": "بحث...",
    "No results found": "لم يتم العثور على نتائج",
    "Read more": "اقرأ المزيد",
    "Share": "شارك",
    "Tags": "علامات",
    "Recent Posts": "المشاركات الأخيرة",
    "Popular Posts": "المشاركات الشائعة",
    "Categories": "فئات",
    "Latest News": "أحدث الأخبار",
    "Our Services": "خدماتنا",
    "Make Appointment": "حجز موعد",
    "Find a Doctor": "البحث عن طبيب",
    "Book Online": "حجز عبر الإنترنت",
    "View All": "عرض الكل",
    "Submit": "إرسال",
    "Name": "اسم",
    "Email": "بريد إلكتروني",
    "Password": "كلمة المرور",
    "Role": "وظيفة",
    "Patient": "مريض",
    "Doctor": "طبيب",
    "Admin": "مسؤول",
    "Confirm Password": "تأكيد كلمة المرور",
    "Please enter your name": "الرجاء إدخال اسمك",
    "Please enter your email": "الرجاء إدخال بريدك الإلكتروني",
    "Please enter your password": "الرجاء إدخال كلمة مرورك",
    "Please select a role": "الرجاء تحديد دور",
    "Please confirm your password": "الرجاء تأكيد كلمة مرورك",
    "Passwords must match": "يجب أن تتطابق كلمات المرور",
    "Register as a new user": "تسجيل كمستخدم جديد",
    "Already have an account?": "هل لديك حساب بالفعل؟",
    "Login here": "تسجيل الدخول هنا",
    "Remember me": "تذكرنى",
    "Forgot password?": "هل نسيت كلمة المرور؟",
    "Login to your account": "تسجيل الدخول إلى حسابك",
    "Do not have an account?": "ليس لديك حساب؟",
    "Register here": "سجل هنا",
    "Dashboard": "لوحة القيادة",
    "Profile": "الملف الشخصي",
    "Appointments": "المواعيد",
    "Medical Records": "السجلات الطبية",
    "Billing": "الفواتير",
    "Notifications": "الإشعارات",
    "Welcome back": "مرحبا بعودتك",
    "Total Patients": "إجمالي عدد المرضى",
    "New Appointments": "مواعيد جديدة",
    "Unread Messages": "رسائل غير مقروءة",
    "View Details": "عرض التفاصيل",
    "Next Appointment": "الموعد القادم",
    "No upcoming appointments": "لا توجد مواعيد قادمة",
    "Last Appointment": "آخر موعد",
    "No past appointments": "لا توجد مواعيد سابقة",
    "Edit": "تعديل",
    "Update Profile": "تحديث الملف الشخصي",
    "Cancel": "إلغاء",
    "Specialization": "تخصص",
    "Bio": "السيرة الذاتية",
    "Patients": "المرضى",
    "Years of Experience": "سنوات الخبرة",
    "Assigned Doctor": "الطبيب المعين",
    "Upcoming Appointment": "الموعد القادم",
    "Last Login": "آخر تسجيل دخول",
    "Manage Settings": "إدارة الإعدادات",
    "Permissions": "أذونات",
    "Enable": "تمكين",
    "Disable": "تعطيل",
    "Create New Post": "إنشاء منشور جديد",
    "Title": "عنوان",
    "Content": "محتوى",
    "Excerpt": "مقتطف",
    "Author": "مؤلف",
    "Published Date": "تاريخ النشر",
    "Image URL": "عنوان URL للصورة",
    "Enter tags separated by commas": "أدخل العلامات مفصولة بفواصل",
    "Publish": "نشر",
    "Update Post": "تحديث المنشور",
    "Delete Post": "حذف المنشور",
    "Are you sure you want to delete this post?": "هل أنت متأكد أنك تريد حذف هذا المنشور؟",
    "Yes, Delete": "نعم، احذف",
    "No, Cancel": "لا، إلغاء",
    "Search Users": "البحث عن المستخدمين",
    "Search by name or email": "البحث بالاسم أو البريد الإلكتروني",
    "Search Posts": "البحث عن المشاركات",
    "Search by title or content": "البحث بالعنوان أو المحتوى",
    "Create User": "إنشاء مستخدم",
    "Update User": "تحديث المستخدم",
    "Delete User": "حذف المستخدم",
    "Are you sure you want to delete this user?": "هل أنت متأكد أنك تريد حذف هذا المستخدم؟",
    "Psychological Tests": "الاختبارات النفسية",
    "Take one of our psychological tests to learn more about yourself.": "خذ أحد اختباراتنا النفسية لمعرفة المزيد عن نفسك.",
    "Depression Test": "اختبار الاكتئاب",
    "Anxiety Test": "اختبار القلق",
    "Personality Test": "اختبار الشخصية",
    "ADHD Test": "اختبار فرط الحركة ونقص الانتباه",
    "Psychological State Test for Children": "اختبار الحالة النفسية للأطفال",
    "Jealousy Test": "اختبار الغيرة",
    "Love Test": "اختبار الحب",
    "Passion Test": "اختبار الشغف",
    "This test will help assess potential symptoms. Results are not a diagnosis.": "سيساعد هذا الاختبار في تقييم الأعراض المحتملة. النتائج ليست تشخيصًا.",
    "Take this test to assess your": "خذ هذا الاختبار لتقييم",
    "The test consists of": "يتكون الاختبار من",
    "questions and will take approximately": "أسئلة وسيستغرق حوالي",
    "minutes to complete.": "دقائق للإكمال.",
    "Please answer each question honestly for the most accurate results.": "يرجى الإجابة على كل سؤال بصدق للحصول على أدق النتائج.",
    "Start Test": "ابدأ الاختبار",
    "Back": "رجوع",
    "Select": "اختر",
    "Question": "سؤال",
    "of": "من",
    "Not at all": "لا على الإطلاق",
    "Several days": "عدة أيام",
    "More than half the days": "أكثر من نصف الأيام",
    "Nearly every day": "تقريبًا كل يوم",
    "Test Results": "نتائج الاختبار",
    "This test is for educational purposes only and should not be used for self-diagnosis. Please consult with a mental health professional for proper diagnosis and treatment.": "هذا الاختبار لأغراض تعليمية فقط ولا ينبغي استخدامه للتشخيص الذاتي. يرجى استشارة أخصائي الصحة النفسية للتشخيص والعلاج المناسب.",
    "Restart Test": "إعادة الاختبار",
    "Choose Another Test": "اختر اختبارًا آخر",
    "Your score is": "نتيجتك هي",
    "Please consult with a professional for interpretation.": "يرجى استشارة متخصص للتفسير.",
    "Test completed!": "اكتمل الاختبار!",
    "Minimal or no depression": "اكتئاب ضئيل أو معدوم",
    "Mild depression": "اكتئاب خفيف",
    "Moderate depression": "اكتئاب متوسط",
    "Severe depression": "اكتئاب شديد",
    "Minimal or no anxiety": "قلق ضئيل أو معدوم",
    "Mild anxiety": "قلق خفيف",
    "Moderate anxiety": "قلق متوسط",
    "Severe anxiety": "قلق شديد",
    "I feel sad or down most of the day": "أشعر بالحزن أو الاكتئاب معظم اليوم",
    "I have lost interest in activities I used to enjoy": "فقدت الاهتمام بالأنشطة التي كنت أستمتع بها",
    "I have trouble sleeping or sleep too much": "أعاني من صعوبة في النوم أو أنام كثيرًا",
    "I feel tired or have little energy": "أشعر بالتعب أو لدي طاقة قليلة",
    "I have poor appetite or am overeating": "لدي شهية ضعيفة أو أفرط في تناول الطعام",
    "I feel nervous or anxious": "أشعر بالتوتر أو القلق",
    "I worry too much about different things": "أقلق كثيرًا بشأن أشياء مختلفة",
    "I have trouble relaxing": "أجد صعوبة في الاسترخاء",
    "I feel restless and have trouble sitting still": "أشعر بعدم الراحة وأجد صعوبة في الجلوس ساكنًا",
    "I am easily annoyed or irritable": "أنزعج أو أتضايق بسهولة",
    "I enjoy being the center of attention": "أستمتع بكوني محور الاهتمام",
    "I prefer quiet, solitary activities": "أفضل الأنشطة الهادئة والمنفردة",
    "I consider myself organized and detail-oriented": "أعتبر نفسي منظم ومهتم بالتفاصيل",
    "I am comfortable in new social situations": "أشعر بالراحة في المواقف الاجتماعية الجديدة",
    "I am more practical than creative": "أنا أكثر عملية من كوني مبدعًا",
    "I have difficulty maintaining attention": "أجد صعوبة في الحفاظ على الانتباه",
    "I am easily distracted": "أتشتت بسهولة",
    "I struggle to follow through on tasks": "أكافح لإكمال المهام",
    "I frequently lose things necessary for tasks": "كثيرًا ما أفقد الأشياء الضرورية للمهام",
    "I often fidget or feel restless": "غالبًا ما أتململ أو أشعر بعدم الراحة",
    "The child has difficulty concentrating": "يجد الطفل صعوبة في التركيز",
    "The child seems worried or anxious": "يبدو الطفل قلقًا أو متوترًا",
    "The child has frequent mood swings": "يعاني الطفل من تقلبات مزاجية متكررة",
    "The child has trouble making friends": "يجد الطفل صعوبة في تكوين صداقات",
    "The child has lost interest in activities they used to enjoy": "فقد الطفل الاهتمام بالأنشطة التي كان يستمتع بها",
    "I often worry about my partner being unfaithful": "غالبًا ما أقلق بشأن خيانة شريكي",
    "I check my partner's phone or social media": "أتفقد هاتف شريكي أو وسائل التواصل الاجتماعي الخاصة به",
    "I feel uncomfortable when my partner talks to others": "أشعر بعدم الارتياح عندما يتحدث شريكي مع الآخرين",
    "I get upset when my partner gives attention to others": "أنزعج عندما يعطي شريكي اهتمامًا للآخرين",
    "I often need reassurance from my partner": "غالبًا ما أحتاج إلى تطمينات من شريكي",
    "I think about this person constantly": "أفكر في هذا الشخص باستمرار",
    "I feel happy when I'm with this person": "أشعر بالسعادة عندما أكون مع هذا الشخص",
    "I prioritize this person's needs over my own": "أعطي أولوية لاحتياجات هذا الشخص على احتياجاتي",
    "I can see a future with this person": "أستطيع أن أرى مستقبلاً مع هذا الشخص",
    "I accept this person's flaws": "أتقبل عيوب هذا الشخص",
    "I lose track of time when engaged in this activity": "أفقد الإحساس بالوقت عندما أنشغل بهذا النشاط",
    "I feel energized when doing this activity": "أشعر بالنشاط عند ممارسة هذا النشاط",
    "I constantly want to improve in this area": "أرغب باستمرار في التحسن في هذا المجال",
    "I think about this activity even when not doing it": "أفكر في هذا النشاط حتى عندما لا أمارسه",
    "I would do this activity even if I wasn't paid or recognized for it": "سأمارس هذا النشاط حتى لو لم أتقاضى أجرًا أو أحصل على تقدير مقابل ذلك",
    "english": "الإنجليزية",
    "arabic": "العربية",
    "login": "تسجيل الدخول",
    "signup": "تسجيل",
    "my_account": "حسابي",
    "admin_panel": "لوحة الإدارة",
    "profile": "الملف الشخصي",
    "logout": "تسجيل الخروج",
    "mental_health_resources": "موارد الصحة النفسية",
    "explore_mental_health_blog": "استكشف مدونة الصحة النفسية",
    "discover_insights": "اكتشف الرؤى والنصائح والمعلومات لدعم رحلة صحتك النفسية",
    "search_articles": "البحث في المقالات...",
    "no_articles_found": "لم يتم العثور على مقالات",
    "try_adjusting_search": "حاول تعديل البحث أو إزالة الفلاتر"
  },
};

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
