
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdgxtocfaynhwebjkysp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkZ3h0b2NmYXluaHdlYmpreXNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MjI3NTMsImV4cCI6MjA2MjQ5ODc1M30.6b5Z2BZjnfsW-IwJUeGUcteHFYGBiKDCdwb2xyuzl1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
